### ISSUE TITLE
Create UI/UX for login page

### ISSUE THREAD

**Issue by Bratah123** [Bratah123/AniFam#21]
See Proposal Doc for initial Login page design, consider using a collage of images in the background!

**Comment by Bratah123** [comment]
Efforts towards this issue has been made as of commit: https://github.com/Bratah123/AniFam/commit/b3104746652c2aac0a690a9d0595046057578d68

**Comment by adykrni** [comment]
hey I would like to contribute, where can I find the Proposal Doc?

**Comment by Bratah123** [comment]
> hey I would like to contribute, where can I find the Proposal Doc?

Yes! The design/proposal doc is actually quite extensive, and the login screen diagrams are not actually on here, but for the login page, we want to model it after [JellyFin's Login](https://demo.jellyfin.org/stable/web/index.html#!/login.html?serverid=713dc3fe952b438fa70ed35e4ef0525a)

You can find the doc [here.](https://docs.google.com/document/d/1FM5WCrVKBZVxV4FH47GF7I_KBe0uLi07GIV8XE_-x9k/edit?usp=sharing)

**Comment by Bratah123** [comment]
Proprietary UI/UX is done for Login Page as of commit: cc86ff991fa10d5d2c20c9095420d3aae6881b82
